language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install hwloc

script: 
  - mkdir -p build 
  - cd build 
  - ../configure --enable-debug --enable-gcc-coverage
  - make 
  - make test

after_success:
  - if [ "$CXX" == "g++" ]; then coveralls -r ../ --gcov-options '\-lp'; fi