language: cpp

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install hwloc
  - yes | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq

script: 
  - mkdir -p build 
  - cd build 
  - ../configure --enable-debug --enable-gcc-coverage
  - make 
  - make test

after_success:
  - if [ "$CXX" == "g++" ]; then coveralls -r ../ --gcov-options '\-lp'; fi